name: SimplePrefix
main: com.flabaliki.simpleprefix.SimplePrefix
version: 2.5.2
api-version: 1.13
softdepend: [Vault]
commands:
    spr:
        description: Multiple commands, use '/spr help' to see all.
        usage: "/spr help"